// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/gluonfield/jaz-tasks/backend/internal/storage"
	"github.com/gluonfield/jaz-tasks/backend/internal/tracker"
)

type CommentPayload struct {
	Comment *storage.Comment `json:"comment"`
	Success bool             `json:"success"`
}

type CommentUpdateInput struct {
	Body graphql.Omittable[*string] `json:"body,omitempty"`
}

type CyclePayload struct {
	Cycle   *storage.Cycle `json:"cycle,omitempty"`
	Success bool           `json:"success"`
}

type DeletePayload struct {
	EntityID string `json:"entityId"`
	Success  bool   `json:"success"`
}

type IssueArchivePayload struct {
	Entity  *storage.Issue `json:"entity,omitempty"`
	Success bool           `json:"success"`
}

type IssueBatchCreateInput struct {
	Issues []tracker.IssueCreateInput `json:"issues"`
}

type IssueBatchPayload struct {
	Issues  []storage.Issue `json:"issues"`
	Success bool            `json:"success"`
}

type IssueLabelPayload struct {
	IssueLabel *storage.IssueLabel `json:"issueLabel"`
	Success    bool                `json:"success"`
}

type IssueLabelUpdateInput struct {
	Color       graphql.Omittable[*string] `json:"color,omitempty"`
	Description graphql.Omittable[*string] `json:"description,omitempty"`
	Name        graphql.Omittable[*string] `json:"name,omitempty"`
	ParentID    graphql.Omittable[*string] `json:"parentId,omitempty"`
}

type IssuePayload struct {
	Issue   *storage.Issue `json:"issue,omitempty"`
	Success bool           `json:"success"`
}

type IssueUpdateInput struct {
	AddedLabelIds   graphql.Omittable[[]string]   `json:"addedLabelIds,omitempty"`
	AssigneeID      graphql.Omittable[*string]    `json:"assigneeId,omitempty"`
	CycleID         graphql.Omittable[*string]    `json:"cycleId,omitempty"`
	Description     graphql.Omittable[*string]    `json:"description,omitempty"`
	DueDate         graphql.Omittable[*time.Time] `json:"dueDate,omitempty"`
	Estimate        graphql.Omittable[*int32]     `json:"estimate,omitempty"`
	LabelIds        graphql.Omittable[[]string]   `json:"labelIds,omitempty"`
	ParentID        graphql.Omittable[*string]    `json:"parentId,omitempty"`
	Priority        graphql.Omittable[*int32]     `json:"priority,omitempty"`
	ProjectID       graphql.Omittable[*string]    `json:"projectId,omitempty"`
	RemovedLabelIds graphql.Omittable[[]string]   `json:"removedLabelIds,omitempty"`
	SortOrder       graphql.Omittable[*float64]   `json:"sortOrder,omitempty"`
	StateID         graphql.Omittable[*string]    `json:"stateId,omitempty"`
	TeamID          graphql.Omittable[*string]    `json:"teamId,omitempty"`
	Title           graphql.Omittable[*string]    `json:"title,omitempty"`
}

type Mutation struct {
}

type OrganizationInviteCreateInput struct {
	Email string `json:"email"`
}

type OrganizationInvitePayload struct {
	OrganizationInvite *storage.WorkspaceInvite `json:"organizationInvite"`
	Success            bool                     `json:"success"`
}

type OrganizationPayload struct {
	Organization *storage.Workspace `json:"organization,omitempty"`
	Success      bool               `json:"success"`
}

type ProjectPayload struct {
	Project *storage.Project `json:"project,omitempty"`
	Success bool             `json:"success"`
}

type ProjectUpdateInput struct {
	Color       graphql.Omittable[*string]    `json:"color,omitempty"`
	Description graphql.Omittable[*string]    `json:"description,omitempty"`
	Icon        graphql.Omittable[*string]    `json:"icon,omitempty"`
	LeadID      graphql.Omittable[*string]    `json:"leadId,omitempty"`
	Name        graphql.Omittable[*string]    `json:"name,omitempty"`
	Priority    graphql.Omittable[*int32]     `json:"priority,omitempty"`
	StartDate   graphql.Omittable[*time.Time] `json:"startDate,omitempty"`
	StatusID    graphql.Omittable[*string]    `json:"statusId,omitempty"`
	TargetDate  graphql.Omittable[*time.Time] `json:"targetDate,omitempty"`
	TeamIds     graphql.Omittable[[]string]   `json:"teamIds,omitempty"`
}

type Query struct {
}

type TeamPayload struct {
	Success bool          `json:"success"`
	Team    *storage.Team `json:"team,omitempty"`
}

type WorkflowStatePayload struct {
	Success       bool                   `json:"success"`
	WorkflowState *storage.WorkflowState `json:"workflowState"`
}

type PaginationOrderBy string

const (
	PaginationOrderByCreatedAt PaginationOrderBy = "createdAt"
	PaginationOrderByUpdatedAt PaginationOrderBy = "updatedAt"
)

var AllPaginationOrderBy = []PaginationOrderBy{
	PaginationOrderByCreatedAt,
	PaginationOrderByUpdatedAt,
}

func (e PaginationOrderBy) IsValid() bool {
	switch e {
	case PaginationOrderByCreatedAt, PaginationOrderByUpdatedAt:
		return true
	}
	return false
}

func (e PaginationOrderBy) String() string {
	return string(e)
}

func (e *PaginationOrderBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaginationOrderBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaginationOrderBy", str)
	}
	return nil
}

func (e PaginationOrderBy) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaginationOrderBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaginationOrderBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
