/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppMyIssuesRouteImport } from './routes/_app/my-issues'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppViewsRouteImport } from './routes/_app/views'
import { Route as AppIssueIdentifierRouteImport } from './routes/_app/issue.$identifier'
import { Route as AppProjectSlugIdRouteImport } from './routes/_app/project.$slugId'
import { Route as AppViewViewIdRouteImport } from './routes/_app/view.$viewId'
import { Route as AppTeamTeamKeyViewRouteImport } from './routes/_app/team.$teamKey.$view'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppMyIssuesRoute = AppMyIssuesRouteImport.update({
  id: '/my-issues',
  path: '/my-issues',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppViewsRoute = AppViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => AppRoute,
} as any)
const AppIssueIdentifierRoute = AppIssueIdentifierRouteImport.update({
  id: '/issue/$identifier',
  path: '/issue/$identifier',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectSlugIdRoute = AppProjectSlugIdRouteImport.update({
  id: '/project/$slugId',
  path: '/project/$slugId',
  getParentRoute: () => AppRoute,
} as any)
const AppViewViewIdRoute = AppViewViewIdRouteImport.update({
  id: '/view/$viewId',
  path: '/view/$viewId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamTeamKeyViewRoute = AppTeamTeamKeyViewRouteImport.update({
  id: '/team/$teamKey/$view',
  path: '/team/$teamKey/$view',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/inbox': typeof AppInboxRoute
  '/my-issues': typeof AppMyIssuesRoute
  '/projects': typeof AppProjectsRoute
  '/views': typeof AppViewsRoute
  '/issue/$identifier': typeof AppIssueIdentifierRoute
  '/project/$slugId': typeof AppProjectSlugIdRoute
  '/view/$viewId': typeof AppViewViewIdRoute
  '/team/$teamKey/$view': typeof AppTeamTeamKeyViewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/inbox': typeof AppInboxRoute
  '/my-issues': typeof AppMyIssuesRoute
  '/projects': typeof AppProjectsRoute
  '/views': typeof AppViewsRoute
  '/': typeof AppIndexRoute
  '/issue/$identifier': typeof AppIssueIdentifierRoute
  '/project/$slugId': typeof AppProjectSlugIdRoute
  '/view/$viewId': typeof AppViewViewIdRoute
  '/team/$teamKey/$view': typeof AppTeamTeamKeyViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/my-issues': typeof AppMyIssuesRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/views': typeof AppViewsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/issue/$identifier': typeof AppIssueIdentifierRoute
  '/_app/project/$slugId': typeof AppProjectSlugIdRoute
  '/_app/view/$viewId': typeof AppViewViewIdRoute
  '/_app/team/$teamKey/$view': typeof AppTeamTeamKeyViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/inbox'
    | '/my-issues'
    | '/projects'
    | '/views'
    | '/issue/$identifier'
    | '/project/$slugId'
    | '/view/$viewId'
    | '/team/$teamKey/$view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/inbox'
    | '/my-issues'
    | '/projects'
    | '/views'
    | '/'
    | '/issue/$identifier'
    | '/project/$slugId'
    | '/view/$viewId'
    | '/team/$teamKey/$view'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/inbox'
    | '/_app/my-issues'
    | '/_app/projects'
    | '/_app/views'
    | '/_app/'
    | '/_app/issue/$identifier'
    | '/_app/project/$slugId'
    | '/_app/view/$viewId'
    | '/_app/team/$teamKey/$view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-issues': {
      id: '/_app/my-issues'
      path: '/my-issues'
      fullPath: '/my-issues'
      preLoaderRoute: typeof AppMyIssuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/views': {
      id: '/_app/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof AppViewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issue/$identifier': {
      id: '/_app/issue/$identifier'
      path: '/issue/$identifier'
      fullPath: '/issue/$identifier'
      preLoaderRoute: typeof AppIssueIdentifierRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/project/$slugId': {
      id: '/_app/project/$slugId'
      path: '/project/$slugId'
      fullPath: '/project/$slugId'
      preLoaderRoute: typeof AppProjectSlugIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/view/$viewId': {
      id: '/_app/view/$viewId'
      path: '/view/$viewId'
      fullPath: '/view/$viewId'
      preLoaderRoute: typeof AppViewViewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/$teamKey/$view': {
      id: '/_app/team/$teamKey/$view'
      path: '/team/$teamKey/$view'
      fullPath: '/team/$teamKey/$view'
      preLoaderRoute: typeof AppTeamTeamKeyViewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInboxRoute: typeof AppInboxRoute
  AppMyIssuesRoute: typeof AppMyIssuesRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppViewsRoute: typeof AppViewsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppIssueIdentifierRoute: typeof AppIssueIdentifierRoute
  AppProjectSlugIdRoute: typeof AppProjectSlugIdRoute
  AppViewViewIdRoute: typeof AppViewViewIdRoute
  AppTeamTeamKeyViewRoute: typeof AppTeamTeamKeyViewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInboxRoute: AppInboxRoute,
  AppMyIssuesRoute: AppMyIssuesRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppViewsRoute: AppViewsRoute,
  AppIndexRoute: AppIndexRoute,
  AppIssueIdentifierRoute: AppIssueIdentifierRoute,
  AppProjectSlugIdRoute: AppProjectSlugIdRoute,
  AppViewViewIdRoute: AppViewViewIdRoute,
  AppTeamTeamKeyViewRoute: AppTeamTeamKeyViewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
